server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Delivery
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**, 
        - id: OverseasDelivery
          uri: http://localhost:8084
          predicates:
            - Path=/overseasDeliveries/**, 
        - id: frontend
          uri: http://localhost:8081
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, 
        - id: OverseasDelivery
          uri: http://overseasDelivery:8080
          predicates:
            - Path=/overseasDeliveries/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
